M48
; DRILL file {KiCad 9.0.0-9.0.0-2~ubuntu24.04.1} date 2025-03-10T11:02:10+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-10T11:02:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0-9.0.0-2~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.950
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.250
%
G90
G05
T1
X78.274Y-135.465
T2
X78.274Y-142.665
T3
X74.0Y-63.75
X74.0Y-156.25
X226.0Y-63.75
X226.0Y-156.25
T4
X72.136Y-76.45
X72.136Y-89.15
M30
